# Generated by Django 6.0.7 on 2026-07-27 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_about_remove_project_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='github_url',
            new_name='github',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='live_url',
            new_name='linkedin',
        ),
    ]
