# Generated by Django 6.0.7 on 2026-08-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
