# Generated by Django 6.0.7 on 2026-08-09 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_project_technologies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('education_type', models.CharField(choices=[('degree', "Bachelor's Degree"), ('certificate', 'Certificate'), ('course', 'Course')], max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
