# Generated by Django 6.0.7 on 2026-08-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='whatsapp',
            field=models.URLField(blank=True),
        ),
    ]
