# Generated by Django 6.0.7 on 2026-08-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_about_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='about',
            name='job_title',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='about',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='profile/'),
        ),
    ]
