# Generated by Django 6.0.7 on 2026-08-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_about_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('github', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('whatsapp', models.URLField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='about',
            name='email',
        ),
        migrations.RemoveField(
            model_name='about',
            name='github',
        ),
        migrations.RemoveField(
            model_name='about',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='about',
            name='whatsapp',
        ),
    ]
